TugasDua/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import halaman_profile.urls as profile
import cari_mahasiswa.urls as cari_mahasiswa
import halamanLogin.urls as halamanLogin
import halamanStatus.urls as halamanStatus
import halamanRiwayat.urls as halamanRiwayat

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(halamanLogin,namespace='halamanLogin')),
    url(r'^teman/', include(cari_mahasiswa,namespace='teman')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^halamanStatus', include(halamanStatus,namespace='halamanStatus')),
    url(r'^halamanRiwayat/', include(halamanRiwayat,namespace="halamanRiwayat")),
]

halamanLogin/urls.py
from django.conf.urls import url
from .views import index, login
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', auth_logout, name='logout'),
    
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

halamanLogin/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	nama = models.CharField('Nama', max_length=200)
	kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True)
	role = models.CharField('Role', max_length=100)

halamanLogin/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.

response = {'logged_in' : False}

def index(request):
    html = 'session/home.html'
    return render(request, html, response)

def login(request):
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('halamanLogin:index'))
    else:
        html = 'session/login.html'
        return render(request, html, response)

halamanLogin/templates/session/home.html
{% extends "layout/base.html" %}
{% block content %}

<section id="fh5co-home" data-section="home" style="background-image: url(https://cdn-images-1.medium.com/max/2000/1*X0YAhnDmAmUXec83Y1IDZA.jpeg);" data-stellar-background-ratio="0.5">
  <div class="gradient"></div>
  <div class="container">
    <div class="text-wrap">
      <div class="text-inner">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
              {% if 'user_login' in request.session %}
              {% else %}
            <h1 class="to-animate">Login disini</h1>
            {% endif %}
            <div class="call-to-action">
                {% if 'user_login' in request.session %}
                
                <div class="demo to-animate">{% include "../partials/header.html" %}</div>
                <a href="/logout" class="demo to-animate">Logout</a>
                
                {% else %}
              <a href="/login" id="login-mhs" class="demo to-animate">Login Mahasiswa</a>
              <a href="#" class="download to-animate">Login Perusahaan</a>
              {% endif %}
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>



{% endblock %}

halamanLogin/templates/session/login.html
{% extends "layout/base.html" %}
{% block content %}
<section id="fh5co-home" data-section="home" style="background-image: url(https://cdn-images-1.medium.com/max/2000/1*X0YAhnDmAmUXec83Y1IDZA.jpeg);" data-stellar-background-ratio="0.5">
    <div class="gradient"></div>
    <div class="container">
      <div class="text-wrap">
        <div class="text-inner">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
           
                <div class="form">
                        <form class="login-form" action="{% url 'halamanLogin:auth_login' %}" method="POST">
                            {% csrf_token %}
                            <p>
                                
                                <input type="text" placeholder = "username" id="username" name="username" required>
                            </p>
                            <p>
                                <input type="password" placeholder="password" id="password" name="password" required>
                            </p>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>
                        </div>
        </div>
      </div>
    </div>
  </section>
  <script>
    
{% endblock %}