TugasDua/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import halaman_profile.urls as profile
import cari_mahasiswa.urls as cari_mahasiswa
import halamanLogin.urls as halamanLogin
import halamanStatus.urls as halamanStatus
import halamanRiwayat.urls as halamanRiwayat

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(halamanLogin,namespace='halamanLogin')),
    url(r'^teman/', include(cari_mahasiswa,namespace='teman')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^halamanStatus', include(halamanStatus,namespace='halamanStatus')),
    url(r'^halamanRiwayat/', include(halamanRiwayat,namespace="halamanRiwayat")),
]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index, edit, addToModel

urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^edit/', edit, name='edit'),
	url(r'^addtomodel/', addToModel, name='addtomodel'),
]

halaman_profile/models.py
from django.db import models

# Create your models here.
class UserProfile(models.Model):
    username = models.CharField(max_length=20,default="Kosong")
    name = models.CharField(max_length=100,default="Kosong")
    npm = models.CharField(max_length=15,default="Kosong")
    keahlian = models.CharField(max_length=250,default="Kosong")
    level = models.CharField(max_length=250,default="Kosong")
    email = models.TextField(default="Kosong")
    linkedin = models.CharField(max_length=250,default="Kosong")
    added_at = models.DateField(auto_now_add=True)
	
    def as_dict(self):
            return {
                "username": self.username,
                "name": self.npm,
                "npm": self.npm,
                "keahlian": self.keahlian,
                "email": self.email,
                "linkedin": self.linkedin,
            }

halaman_profile/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseNotFound
from .models import UserProfile
from django.views.decorators.csrf import csrf_exempt
from halamanLogin.models import User

# Create your views here.
response={}
def index(request):
    if get_data_user(request, 'user_login'):
        set_data_for_session(request)
        npm = get_data_user(request, 'kode_identitas')
        if(not UserProfile.objects.filter(npm=npm).exists()):
            UserProfile(npm=npm).save()
			
        user = UserProfile.objects.filter(npm=npm).get()
        
        response["user"] = user
        response["npm"] = npm
        html = "halaman_profile/profile.html"
        return render(request, html, response)
    else:
        response['login'] = False
        html = 'session/home.html'
        return render(request, html, response)

		
@csrf_exempt
def addToModel(request):
    npm = response['npm']
    name = request.POST['name']
    email = request.POST['email']
    linkedin = request.POST['linkedin']
    keahlian = request.POST['keahlian']
    level = request.POST['level']
 
    UserProfile.objects.filter(npm=npm).update(name=name, email=email, linkedin=linkedin, keahlian=keahlian, level=level)
	
    return HttpResponseRedirect('/profile/edit')
def edit(request):
    response={}
    html = "halaman_profile/edit.html"
    return render(request, html, response)
	
def set_data_for_session(request):
	response['author'] = get_data_user(request, 'user_login')
	response['kode_identitas'] = request.session['kode_identitas']
	response['role'] = request.session['role']
	
def get_data_user(request, tipe):
	data = None
	if tipe == "user_login" and 'user_login' in request.session:
		data = request.session['user_login']
	elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
		data = request.session['kode_identitas']
	elif tipe == "role" and 'role' in request.session:
		data = request.session['role']
	return data

	

halaman_profile/templates/halaman_profile/edit.html
{% extends "halaman_profile/layout/base.html" %}

{% block content %}
<div class="container">
<div id="b1">
	<img></img>
	<button class="btn btn-primary btn-info btn-lg" onclick="simpanData()">Simpan</button>
	<a class="btn btn-primary btn-danger btn-lg" href="../">Keluar</a>
</div>

<div class="linkedin">

</div>

<br>
<div class="select">
<div class="keahlian"> KEAHLIAN : 
<select class="program">
	<option>JAVA</option>
	<option>C#</option>
	<option>C++</option>
	<option>Python</option>
	<option>Erlang</option>
	<option>Kotlin</option>
</select>
</div>

<br>
<div> LEVEL : 
<select class="level">
	<option>Beginner</option>
	<option>Intermediate</option>
	<option>Advanced</option>
	<option>Expert</option>
	<option>Legend</option>
</select>
</div>

<hr>
<script type="in/Login"></script>
</div>
</div>

<div id="profileData" style="display: block;">
</div>

<script type="text/javascript" src="//platform.linkedin.com/in.js">
	api_key: 81vxovqkrgmm5v
    authorize: true
    onLoad: onLinkedInLoad
	scope: r_basicprofile r_emailaddress
</script>
{% endblock %}

halaman_profile/templates/halaman_profile/profile.html
{% extends "halaman_profile/layout/base.html" %}

{% block content %}
<a class="btn btn-primary btn-info btn-lg" href="{% url "profile:edit" %}" id="editP">EDIT PROFILE</a>

<div class="profil">
	<h3>Nama : {{user.name}} </h3>
	<h3>NPM : {{npm}} </h3>
	<h3>Keahlian : {{user.keahlian}} </h3>
	<h3>Email : {{user.email}} </h3>
	<h3>Profile : {{user.linkedin}}</h3>
</div>

{% endblock %}

halaman_profile/templates/halaman_profile/utama.html
{% extends "halaman_profile/layout/base.html" %}

{% block content %}

<div class="container">
                    
      

<div>
    <h2>Welcome,</h2>
    <h1 style="margin-bottom:30px">{{name}}</h1>
    <div class="info" style="display:flex">
        <img src="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png" width="15%" height="15%">
        <div class="tombol">
            <button class="btn btn-lg btn-block btn-info" >Lihat Forum</button>
            <a href="/mahasiswa/edit/" class="btn btn-lg btn-block btn-info" >Edit Profile</button>
            <a href="/mahasiswa/custom_auth/logout/" class="btn btn-lg btn-block btn-info" onclick="return confirm('Keluar?')">
            Logout </a>
        </div>
        <div class="status">
            <h1> 0 </h1>
            <h2> Status </h2>
        </div>
    </div>
</div>

<br><br>

<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist" style="border-radius:100px;">
        <li role="presentation" class="active">
            <a class="tabs" href="#profile" aria-controls="home" role="tab" data-toggle="tab"> Profile </a>
        </li>
        <li role="presentation">
            <a class="tabs" href="#history" aria-controls="settings" role="tab" data-toggle="tab"> History </a>
        </li>
        <li role="presentation">
            <a class="tabs" href="#status" aria-controls="settings" role="tab" data-toggle="tab"> Status </a>
        </li>
        <li role="presentation">
            <a class="tabs" href="#friends" aria-controls="settings" role="tab" data-toggle="tab"> Friends </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="profile">
            <div class="panel panel-info">
				<div class="panel-body">
					{% include "halaman_profile/profile.html" %}
				</div>
			</div>

        </div>
		<div role="tabpanel" class="tab-pane fade" id="history">
			<div class="panel panel-info">
				<div class="panel-body">
					
				</div>
			</div>
		</div>
		
		<div role="tabpanel" class="tab-pane fade" id="status">
			<div class="panel panel-info">
				<div class="panel-body">
				</div>

			</div>
		</div>
		
		<div role="tabpanel" class="tab-pane fade" id="friends">
			<div class="panel panel-info">
				<div class="panel-body">
					{% include "cari_mahasiswa/cari_teman.html" %}
				</div>
			</div>
		</div>
	</div>

</div>
{% endblock %}